version: 2
updates:
  # Root package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "poisontr33s"
    assignees:
      - "poisontr33s"

  # CLI package
  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Core package  
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Monitor package
  - package-ecosystem: "npm"
    directory: "/packages/monitor"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Shared package
  - package-ecosystem: "npm"
    directory: "/packages/shared"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Server base package
  - package-ecosystem: "npm"
    directory: "/packages/servers/base"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # DuckDuckGo server package
  - package-ecosystem: "npm"
    directory: "/packages/servers/duckduckgo"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Sequential thinking server package
  - package-ecosystem: "npm"
    directory: "/packages/servers/sequential-thinking"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5