- name: type:feature
  color: 4f8cc9
- name: type:bug
  color: d73a4a
- name: type:chore
  color: cfd3d7
- name: type:doc
  color: 6a737d
- name: status:intake
  color: d4c5f9
- name: status:triage
  color: ebbf23
- name: status:ready
  color: 0e8a16
- name: status:blocked
  color: b60205
- name: status:in-review
  color: fbca04
- name: status:stale
  color: cccccc
- name: priority:p0
  color: b60205
- name: priority:p1
  color: d93f0b
- name: priority:p2
  color: fbca04
- name: epic
  color: 5319e7
- name: branch-family:skyskraperen
  color: 1d76db
- name: branch-family:rustbeltet
  color: 0052cc
- name: system:orchestration
  color: 0e8a16