data:
  - name: "type:bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "type:feature"
    color: "a2eeef"
    description: "New functionality"
  - name: "type:task"
    color: "0366d6"
    description: "Small, actionable work item"
  - name: "type:epic"
    color: "5319e7"
    description: "Large effort broken into tasks"
  - name: "area:frontend"
    color: "1abc9c"
    description: "UI/monitor app (packages/monitor)"
  - name: "area:core"
    color: "0e8a16"
    description: "Core orchestration (packages/core)"
  - name: "area:cli"
    color: "6f42c1"
    description: "CLI tooling (packages/cli)"
  - name: "area:servers"
    color: "fbca04"
    description: "MCP servers (packages/servers/*)"
  - name: "area:shared"
    color: "c5def5"
    description: "Shared libs (packages/shared)"
  - name: "area:docs"
    color: "0052cc"
    description: "Documentation"
  - name: "area:ci"
    color: "5319e7"
    description: "CI/CD workflows"
  - name: "priority:p0"
    color: "b60205"
    description: "Critical"
  - name: "priority:p1"
    color: "d93f0b"
    description: "High"
  - name: "priority:p2"
    color: "e4e669"
    description: "Medium"
  - name: "priority:p3"
    color: "0e8a16"
    description: "Low"
  - name: "status:triage"
    color: "ededed"
    description: "Needs triage"
  - name: "status:blocked"
    color: "d73a4a"
    description: "Blocked by dependency"
  - name: "status:ready"
    color: "0e8a16"
    description: "Ready to pick up"
  - name: "agent:claude"
    color: "2b7489"
    description: "Strategic AI lead - comprehensive analysis and macro-prompt frameworks"
  - name: "agent:copilot"
    color: "24292e"
    description: "Tactical AI assistant - delegated tasks and implementation"
  - name: "agent:gemini"
    color: "5319e7"
    description: "Specialized AI capabilities - domain-specific expertise"
  - name: "agent:codex"
    color: "000000"
    description: "Code generation AI - implementation and documentation"
  - name: "collaboration:symbiotic"
    color: "ff6b35"
    description: "Multi-AI collaborative effort with cross-pollinating intelligence"
  - name: "framework:autonomous"
    color: "7b68ee"  
    description: "Autonomous capability framework - natural language strategic processing"
  - name: "size:XS"
    color: "bfd4f2"
    description: "< 1 hour"
  - name: "size:S"
    color: "bfdadc"
    description: "1-3 hours"
  - name: "size:M"
    color: "c2e0c6"
    description: "Half-day"
  - name: "size:L"
    color: "fef2c0"
    description: "1-2 days"
  - name: "size:XL"
    color: "f9d0c4"
    description: "Multi-day"