# 🏴‍☠️ Captain Guthilda's Universal Development Environment
# Auto-generated by setup-polyglot-paradise.ps1

Write-Host "🏴‍☠️ Activating Captain Guthilda's Polyglot Paradise..." -ForegroundColor Cyan

$ErrorActionPreference = "SilentlyContinue"
$devTools = "C:\Users\erdno\BETTERDOWNLOADSFOLDER\github_repos2025\Restructure-MCP-Orchestration\Restructure-MCP-Orchestration\dev-tools"

# Java 21 + Maven
if (Test-Path "$devTools\java21") {
    $env:JAVA_HOME = "$devTools\java21"
    $env:PATH = "$devTools\java21\bin;$env:PATH"
    Write-Host "☕ Java 21 activated" -ForegroundColor Green
}
if (Test-Path "$devTools\maven") {
    $env:MAVEN_HOME = "$devTools\maven"
    $env:PATH = "$devTools\maven\bin;$env:PATH"
    Write-Host "🔨 Maven activated" -ForegroundColor Green
}

# Node.js + Bun
if (Test-Path "$devTools\node") {
    $env:PATH = "$devTools\node;$env:PATH"
    Write-Host "🟢 Node.js activated" -ForegroundColor Green
}
if (Test-Path "$devTools\bun") {
    $env:PATH = "$devTools\bun;$env:PATH"
    Write-Host "🥖 Bun activated" -ForegroundColor Green
}

# Go
if (Test-Path "$devTools\go") {
    $env:GOROOT = "$devTools\go"
    $env:PATH = "$devTools\go\bin;$env:PATH"
    Write-Host "🐹 Go activated" -ForegroundColor Green
}

# Python
if (Test-Path "$devTools\python") {
    $env:PATH = "$devTools\python;$env:PATH"
    Write-Host "🐍 Python activated" -ForegroundColor Green
}

# Rust
if (Test-Path "$devTools\rust") {
    $env:CARGO_HOME = "$devTools\rust"
    $env:PATH = "$devTools\rust\bin;$env:PATH"
    Write-Host "🦀 Rust activated" -ForegroundColor Green
}

# .NET
if (Test-Path "$devTools\dotnet") {
    $env:DOTNET_ROOT = "$devTools\dotnet"
    $env:PATH = "$devTools\dotnet;$env:PATH"
    Write-Host "🔵 .NET activated" -ForegroundColor Green
}

Write-Host ""
Write-Host "🎉 Polyglot Paradise is ready!" -ForegroundColor Magenta
Write-Host "🎼 Use 'java -jar meta-package-manager\target\meta-orchestrator.jar' to orchestrate all package managers" -ForegroundColor Cyan
