@echo off
REM ????? Captain Guthilda's Universal Development Environment
REM Auto-generated by setup-polyglot-paradise.ps1

echo ????? Activating Captain Guthilda's Polyglot Paradise...

set "devTools=C:\Users\erdno\BETTERDOWNLOADSFOLDER\github_repos2025\Restructure-MCP-Orchestration\Restructure-MCP-Orchestration\dev-tools"

REM Java 21 + Maven
if exist "%devTools%\java21" (
    set "JAVA_HOME=%devTools%\java21"
    set "PATH=%devTools%\java21\bin;%PATH%"
    echo ? Java 21 activated
)
if exist "%devTools%\maven" (
    set "MAVEN_HOME=%devTools%\maven"
    set "PATH=%devTools%\maven\bin;%PATH%"
    echo ?? Maven activated
)

REM Node.js + Bun
if exist "%devTools%\node" (
    set "PATH=%devTools%\node;%PATH%"
    echo ?? Node.js activated
)
if exist "%devTools%\bun" (
    set "PATH=%devTools%\bun;%PATH%"
    echo ?? Bun activated
)

REM Go
if exist "%devTools%\go" (
    set "GOROOT=%devTools%\go"
    set "PATH=%devTools%\go\bin;%PATH%"
    echo ?? Go activated
)

REM Python
if exist "%devTools%\python" (
    set "PATH=%devTools%\python;%PATH%"
    echo ?? Python activated
)

REM Rust
if exist "%devTools%\rust" (
    set "CARGO_HOME=%devTools%\rust"
    set "PATH=%devTools%\rust\bin;%PATH%"
    echo ?? Rust activated
)

REM .NET
if exist "%devTools%\dotnet" (
    set "DOTNET_ROOT=%devTools%\dotnet"
    set "PATH=%devTools%\dotnet;%PATH%"
    echo ?? .NET activated
)

echo.
echo ?? Polyglot Paradise is ready!
echo ?? Use 'java -jar meta-package-manager\target\meta-orchestrator.jar' to orchestrate all package managers
