name: Agent - Gemini (stub)
on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

permissions:
  issues: write
  pull-requests: write

jobs:
  gemini:
    if: contains(github.event.label.name, 'agent:gemini')
    runs-on: ubuntu-latest
    steps:
      - name: Acknowledge and guide
        uses: actions/github-script@v7
        with:
          script: |
            const msg = [
              "Gemini agent stub received.",
              "To enable real runs:",
              "- Add Actions secret GOOGLE_API_KEY",
              "- Approve me to add a small Node entrypoint using @google/generative-ai",
              "- Tell me the exact task scope (summarize, propose diffs, run tests, etc.)"
            ].join("\n");
            if (context.eventName === 'issues') {
              await github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number, body: msg });
            } else {
              await github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.payload.pull_request.number, body: msg });
            }