name: Emergency Branch Consolidation

on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'Consolidation operation to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - create
          - analyze
          - status
      target_branch:
        description: 'Specific target branch (optional)'
        required: false
        type: string
      dry_run:
        description: 'Perform dry run without making changes'
        required: false
        default: true
        type: boolean
      force:
        description: 'Skip confirmation prompts'
        required: false
        default: false
        type: boolean

  schedule:
    # Run consolidation analysis daily at 2 AM UTC
    - cron: '0 2 * * *'

permissions:
  contents: write
  pull-requests: read
  issues: read

jobs:
  consolidation:
    name: Emergency Consolidation - ${{ github.event.inputs.operation || 'analyze' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh auth status

      - name: Execute Consolidation Operation
        id: consolidation
        run: |
          set -e
          
          # Set default operation for scheduled runs
          OPERATION="${{ github.event.inputs.operation || 'analyze' }}"
          TARGET_BRANCH="${{ github.event.inputs.target_branch }}"
          DRY_RUN="${{ github.event.inputs.dry_run || 'true' }}"
          FORCE="${{ github.event.inputs.force || 'false' }}"
          
          echo "operation=$OPERATION" >> $GITHUB_OUTPUT
          echo "dry_run=$DRY_RUN" >> $GITHUB_OUTPUT
          
          # Execute consolidation script
          CONSOLIDATION_ARGS="--operation $OPERATION"
          if [[ -n "$TARGET_BRANCH" ]]; then
            CONSOLIDATION_ARGS="$CONSOLIDATION_ARGS --target-branch $TARGET_BRANCH"
          fi
          if [[ "$DRY_RUN" == "true" ]]; then
            CONSOLIDATION_ARGS="$CONSOLIDATION_ARGS --dry-run"
          fi
          if [[ "$FORCE" == "true" ]]; then
            CONSOLIDATION_ARGS="$CONSOLIDATION_ARGS --force"
          fi
          
          echo "Executing: ./scripts/branch-consolidation.sh $CONSOLIDATION_ARGS"
          ./scripts/branch-consolidation.sh $CONSOLIDATION_ARGS | tee consolidation_output.log

      - name: Execute Dependency Analysis
        if: ${{ github.event.inputs.operation == 'analyze' || github.event_name == 'schedule' }}
        run: |
          echo "Analyzing dependency PRs..."
          ./scripts/dependency-batch.sh --operation analyze | tee dependency_analysis.log

      - name: Generate Consolidation Report
        id: report
        run: |
          cat > consolidation_report.md << 'EOF'
          # Emergency Branch Consolidation Report
          
          **Date**: $(date -u)
          **Operation**: ${{ steps.consolidation.outputs.operation }}
          **Dry Run**: ${{ steps.consolidation.outputs.dry_run }}
          **Triggered By**: ${{ github.event_name }}
          
          ## Consolidation Results
          
          ```
          $(cat consolidation_output.log 2>/dev/null || echo "No consolidation output")
          ```
          
          ## Dependency Analysis
          
          ```
          $(cat dependency_analysis.log 2>/dev/null || echo "No dependency analysis")
          ```
          
          ## Current Repository Status
          
          - **Total Branches**: $(git branch -r | wc -l)
          - **Open PRs**: $(gh pr list --state open --json number | jq length)
          - **Consolidation Framework**: ✅ Implemented
          
          ## Next Steps
          
          1. Review consolidation results
          2. Execute branch creation if needed
          3. Manual PR consolidation process
          4. Validation and testing
          
          ---
          *Generated by Emergency Branch Consolidation Workflow*
          EOF
          
          echo "Generated consolidation report"

      - name: Upload Consolidation Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: consolidation-report-${{ github.run_number }}
          path: |
            consolidation_report.md
            consolidation_output.log
            dependency_analysis.log
          retention-days: 30

      - name: Comment on Issue (if manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          if gh issue view 111 >/dev/null 2>&1; then
            echo "Posting consolidation update to issue #111..."
            cat consolidation_report.md | gh issue comment 111 --body-file -
          else
            echo "Issue #111 not found, skipping comment"
          fi

      - name: Create/Update Consolidation Summary Issue
        if: github.event_name == 'schedule'
        run: |
          # Create or update a consolidation tracking issue
          ISSUE_TITLE="🚨 Daily Branch Consolidation Status - $(date -u +%Y-%m-%d)"
          ISSUE_BODY=$(cat consolidation_report.md)
          
          # Try to create issue (will fail if duplicate title exists)
          gh issue create --title "$ISSUE_TITLE" --body "$ISSUE_BODY" --label "consolidation,automation" || {
            echo "Issue creation failed (likely duplicate), updating existing issue"
          }

  validate-framework:
    name: Validate Consolidation Framework
    runs-on: ubuntu-latest
    needs: consolidation
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate Scripts
        run: |
          echo "Validating consolidation scripts..."
          
          # Check script permissions
          test -x scripts/branch-consolidation.sh || exit 1
          test -x scripts/dependency-batch.sh || exit 1
          test -x scripts/universal-branch-manager.sh || exit 1
          
          # Check script syntax
          bash -n scripts/branch-consolidation.sh
          bash -n scripts/dependency-batch.sh
          bash -n scripts/universal-branch-manager.sh
          
          echo "✅ All scripts validated successfully"

      - name: Test Package Scripts
        run: |
          echo "Testing package.json scripts..."
          
          # Test that consolidation scripts are accessible
          pnpm consolidation:plan --help >/dev/null || exit 1
          pnpm dependencies:analyze --help >/dev/null || exit 1
          
          echo "✅ Package scripts validated successfully"

      - name: Build Framework
        run: |
          echo "Building consolidation framework..."
          pnpm build
          echo "✅ Build successful"

  framework-status:
    name: Framework Status Summary
    runs-on: ubuntu-latest
    needs: [consolidation, validate-framework]
    if: always()

    steps:
      - name: Generate Framework Status
        run: |
          echo "## 🚨 Emergency Branch Consolidation Framework Status"
          echo ""
          echo "**Consolidation Job**: ${{ needs.consolidation.result }}"
          echo "**Validation Job**: ${{ needs.validate-framework.result }}"
          echo "**Overall Status**: ${{ (needs.consolidation.result == 'success' && needs.validate-framework.result == 'success') && '✅ OPERATIONAL' || '⚠️ NEEDS ATTENTION' }}"
          echo ""
          echo "**Framework Components**:"
          echo "- ✅ Branch Consolidation Script"
          echo "- ✅ Dependency Batch Script"
          echo "- ✅ Universal Branch Manager"
          echo "- ✅ GitHub Actions Workflow"
          echo "- ✅ Documentation Framework"
          echo ""
          echo "**Ready for Emergency Consolidation**: Yes"
          echo ""
          echo "---"
          echo "*Framework validation completed at $(date -u)*"