name: Sync labels
on:
  workflow_dispatch:
  push:
    paths:
      - .github/labels.yml
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false