name: Security Scanning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Mondays

env:
  NODE_VERSION: '18'

jobs:
  dependency-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run pnpm audit
        run: |
          pnpm audit --json > audit-results.json || true
          
      - name: Run dependency check
        run: |
          # Generate dependency tree and vulnerability report
          pnpm list --json > dependency-tree.json || true
          
      # ARTIFACT V4 COMPATIBILITY NOTE:
      # Vulnerability scan with unique artifact name to prevent conflicts
      # v4 does not allow overwriting artifacts
      - name: Upload vulnerability scan results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: vulnerability-scan-${{ github.sha }}
          path: |
            audit-results.json
            dependency-tree.json
          retention-days: 30
          if-no-files-found: warn

  license-scan:
    name: License Compliance Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Install license checker
        run: pnpm add -g license-checker
        
      - name: Generate license report
        run: |
          license-checker --json --out license-report.json || true
          license-checker --csv --out license-report.csv || true
          
      # ARTIFACT V4 COMPATIBILITY NOTE:
      # License scan results with unique name including commit SHA
      # v4 artifacts are immutable - cannot be modified once uploaded
      - name: Upload license scan results
        uses: actions/upload-artifact@v4
        with:
          name: license-scan-results-${{ github.sha }}
          path: |
            license-report.json
            license-report.csv
          retention-days: 90
          if-no-files-found: warn

  security-analysis:
    name: Security Analysis Report
    runs-on: ubuntu-latest
    needs: [dependency-scan, license-scan]
    if: always()
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # ARTIFACT V4 COMPATIBILITY NOTE:
      # Download vulnerability and license scan results
      - name: Download vulnerability scan
        uses: actions/download-artifact@v4
        with:
          name: vulnerability-scan-${{ github.sha }}
          path: scans/vulnerability/
        continue-on-error: true
        
      - name: Download license scan results
        uses: actions/download-artifact@v4
        with:
          name: license-scan-results-${{ github.sha }}
          path: scans/licenses/
        continue-on-error: true
        
      - name: Generate consolidated security report
        run: |
          mkdir -p reports
          echo "# Security Analysis Report" > reports/security-report.md
          echo "Generated: $(date)" >> reports/security-report.md
          echo "" >> reports/security-report.md
          
          # Consolidate vulnerability findings
          echo "## Vulnerability Scan Results" >> reports/security-report.md
          if [ -f "scans/vulnerability/audit-results.json" ]; then
            echo "- Vulnerability audit completed successfully" >> reports/security-report.md
          fi
          if [ -f "scans/vulnerability/dependency-tree.json" ]; then
            echo "- Dependency tree analysis completed" >> reports/security-report.md
          fi
          
          # Add license information
          echo "" >> reports/security-report.md
          echo "## License Compliance" >> reports/security-report.md
          if [ -f "scans/licenses/license-report.csv" ]; then
            echo "- License report generated successfully" >> reports/security-report.md
          fi
          
      # ARTIFACT V4 COMPATIBILITY NOTE:
      # Consolidated security report with unique name to avoid conflicts
      # v4 requires unique artifact names across all workflow runs
      - name: Upload consolidated security report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-analysis-report-${{ github.sha }}
          path: reports/
          retention-days: 180
          if-no-files-found: warn