name: Stale
on:
  schedule:
    - cron: "0 2 * * *"
permissions:
  issues: write
  pull-requests: write
jobs:
  mark-stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: status:stale
          stale-pr-label: status:stale
          exempt-issue-labels: priority:p0
          exempt-pr-labels: priority:p0
          stale-issue-message: "Signal fade. Ping hvis fortsatt relevant."
          stale-pr-message: "Glitch detected: PR er inaktiv. Oppdater eller lukk."